### ISSUE TITLE
JSON descriptions and text have words smashed together

### ISSUE THREAD

**Issue by jeryj** [gthmb/bjcp-2015-json#1]
Howdy! I'm using the BJCP JSON file you made to provide some useful info on a little taplist project I'm working on (http://taply.heroku.com), but all the descriptions have words smushed together. Looks like every newline from the XML file got stripped and didn't get replaced with a space.

Also, is there a reason you did: `{"styleguide":{"class":[{"type":"beer",...` instead of `{"styleguide":{"beer":..`?

Cheers!

**Comment by gthmb** [comment]
Hey Jerry, I just pushed up my newest changes to this a few mins ago. I have been tweaking things to use this output in a project, so there a few improvements/changes. 

The spacing issues is resolved, and the I have added back the 'meta' info found in the guidelines (like the introduction, the terms, etc). I might make that an optional build param or something in the future.

Anyway, regarding your question about the array syntax: I am leveraging seth-k's pre-existing XML document for conversion, and it has the the classes of styles (Beer, Mead, Cider) broken out like that. Makes sense IMO.

Cheers. I am traveling this weekend, so limited ability to respond. Hope the new changes help!

**Comment by jeryj** [comment]
Nice! Thanks for working on that. I was motivated and had no idea you'd be so fast to address the issue (impressive!) so I worked on a different model a little last night off of the XML file. You can check it out here: https://gist.github.com/jeryj/6c3ce281f7c62dee4c639786c801ed9d

I'm guessing it would be clutter to add that alternate format in to this project (it's just an array of Categories, and JUST the beer styles), but I can submit a PR if you think it'd be a good addition.

I'll likely move back to your JSON format because it would be nice to load up cider and mead too. Thanks again for your help!
